project_id = "suicqpfijnsortcszqep"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-cancellation-otp]
verify_jwt = false

[functions.verify-cancellation-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-change-email]
verify_jwt = false
