UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/antibiotics.png' WHERE category = 'Antibiotics' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/pain-relief.png' WHERE category = 'Pain Relief' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/cardiac.png' WHERE category IN ('Cardiac', 'Cardiology') AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/vitamins.png' WHERE category = 'Vitamins' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/diabetes.png' WHERE category = 'Diabetes' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/respiratory.png' WHERE category = 'Respiratory' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/allergy.png' WHERE category = 'Allergy' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/gastro.png' WHERE category = 'Gastro' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/first-aid.png' WHERE category = 'First Aid' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/ayurvedic.png' WHERE category = 'Ayurvedic' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/supplements.png' WHERE category = 'Supplements' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/cold-cough.png' WHERE category IN ('Cold & Cough', 'Cold & Flu') AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/antifungal.png' WHERE category = 'Antifungal' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/thyroid.png' WHERE category = 'Thyroid' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/steroids.png' WHERE category = 'Steroids' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/antiseptic.png' WHERE category = 'Antiseptic' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/rehydration.png' WHERE category = 'Rehydration' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/health-wellness.png' WHERE category = 'Health & Wellness' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/general.png' WHERE category = 'General' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/personal-care.png' WHERE category = 'Personal Care' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/anti-inflammatory.png' WHERE category = 'Anti-inflammatory' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/devices.png' WHERE category = 'Devices' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/digestive.png' WHERE category = 'Digestive' AND image_url IS NULL;
UPDATE medicines SET image_url = 'https://suicqpfijnsortcszqep.supabase.co/storage/v1/object/public/medicine-images/anti-nausea.png' WHERE category = 'Anti-nausea' AND image_url IS NULL;
